### ISSUE TITLE
Article landing page: add new line after ORCID link

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/bootstrap3#107]
Related to: https://forum.pkp.sfu.ca/t/multiple-author-issues/51285
ORCID link should be displayed as a block element or have a break line after.

**Comment by NateWr** [comment]
Is this not already the case? https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/objects/article_details.tpl#L135-L142

I believe they may be using an outdated version of the theme.

**Comment by kaitlinnewson** [comment]
@Vitaliy-1 This issue can be closed (I've confirmed in 3.3/3.4 that the ORCID link is displaying on a new line after the author name).
