### ISSUE TITLE
Language block in the sidebar not displaying correctly

### ISSUE THREAD

**Issue by israelcefrin** [pkp/bootstrap3#126]
The language block in the sidebar is not displaying correctly in a multi-journal installation when set to be used in the portal home.

It seems that the container is now getting the width from the inner content. Please see the image.

![bootstrap-language-block](https://user-images.githubusercontent.com/4992902/61237132-24c95380-a710-11e9-9204-4cc1bcd9f30a.png)

**Comment by andjsmit** [comment]
Ran into this issue today. It seems the breaking change was wrapping the header "Language" in a <h2> tag rather than a <span> tag.

**Comment by kaitlinnewson** [comment]
In OJS 3.3 I can only reproduce this in the "small" breakpoint in bootstrap (width 768-991). I've made a minor adjustment to the breakpoint.

PR ready for review @asmecher:
- 3_3_0: https://github.com/pkp/bootstrap3/pull/212

Display before change:

![Screenshot 2024-06-26 at 10 18 09 AM](https://github.com/pkp/bootstrap3/assets/6903515/d690e6f4-9419-4050-970a-a31451ea2aad)

Display after change:

![Screenshot 2024-06-26 at 10 31 40 AM](https://github.com/pkp/bootstrap3/assets/6903515/d4a3b803-c70c-4799-b345-8a870ca51e50)

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson, I've merged https://github.com/pkp/bootstrap3/pull/212. Does this need forward-porting?

**Comment by kaitlinnewson** [comment]
@asmecher Additional PRs added above and ready for review/merge.

**Comment by asmecher** [comment]
Merged both, thanks -- closing!
