### ISSUE TITLE
The getLocalizedSubject() function is returning error

### ISSUE THREAD

**Issue by israelcefrin** [pkp/bootstrap3#132]
Hi @NateWr 

I've enabled the bootstrap3 theme in a Brazilian portugueses journal, this journal accepts submissions in English, however there is none so far. All site seems to work fine but the article detail page is not loading. Checking the logs I've found out that the following code in 
is preventing the journal to show the page:
https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/objects/article_details.tpl#L230

The log file shows :

`PHP Fatal error:  Uncaught Error: Call to undefined method PublishedArticle::getLocalizedSubject()`

I can see tha there is a verification whether getLocalizedSubject is true, but the system is returning a non-existent method. Is it safe to remove this chunk from the theme?

Best,
Israel

**Comment by asmecher** [comment]
I recently merged a change that got rid of the `getLocalizedSubject` function. It wasn't working and wasn't used in the OJS codebase, but I didn't check plugins. Your PRs to resolve this look good to me!

**Comment by kaitlinnewson** [comment]
@asmecher This issue can be closed (resolved in https://github.com/pkp/bootstrap3/pull/136).

**Comment by asmecher** [comment]
Closing, thanks!
