### ISSUE TITLE
in-place edit links are 404

### ISSUE THREAD

**Issue by jnugent** [pkp/bootstrap3#146]
This is probably a minor thing but the built in "edit" links that appear when a user is logged in and looking at pages like submissions, about, etc, no longer resolve to the correct pages in the dashboard.  An example:

https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/pages/submissions.tpl#L70

That should be "context", not "journal".  Likewise, on 

https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/pages/submissions.tpl#L46

That should be "workflow" not "publication".

**Comment by NateWr** [comment]
Thanks, do you know a version number? Some of the URLs changed in v3.2 and in 3.3 we'll be able to point specifically to tabs/sub-tabs in the settings. So I think this will need to be updated for a specific version.

**Comment by jnugent** [comment]
Hi @NateWr  in this case, the journal is 3.2.0-3.

**Comment by kaitlinnewson** [comment]
@asmecher This issue can be closed (original PR was https://github.com/pkp/bootstrap3/pull/102, and these links are confirmed working in 3.3/3.4/main).

**Comment by asmecher** [comment]
Closed, thanks!
