### ISSUE TITLE
Copyright Notice - edit link broken

### ISSUE THREAD

**Issue by israelcefrin** [pkp/bootstrap3#169]
When a logged user attempts to edit "Copyright Notice" section, clicking on "edit" link from frontend interface, it takes the user to a blank screen.

The reason is pointing to:
`/management/settings/journal#policies`
when the correct link should be:
`/management/settings/distribution#permissions
`

The edit link is shown in "Submission" page of the journal.

![image](https://user-images.githubusercontent.com/4992902/120039562-241fca80-bfd3-11eb-9d56-20aecffbaf3c.png)

**Comment by NateWr** [comment]
What version of OJS and Bootstrap3?

**Comment by israelcefrin** [comment]
OJS version: 3.1.1.0 
Bootstrap: 1.1.4.0

**Comment by NateWr** [comment]
I don't think that we'll fix it for 3.1.x. can you reproduce the problem in
3.3.x?

**Comment by israelcefrin** [comment]
Yes, OJS 3.3 shows the same issue using the Bootstrap theme. I've tested on the test-drive install:

https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php/testdrive-journal/about/submissions

**Comment by asmecher** [comment]
Merged, thanks -- please go ahead!

**Comment by kaitlinnewson** [comment]
@asmecher Additional PRs ready for merge and linked above.

**Comment by asmecher** [comment]
Merged, thanks, @kaitlinnewson! Is this ready to be closed?

**Comment by kaitlinnewson** [comment]
@asmecher Yes, ready to close!

**Comment by asmecher** [comment]
Thanks!
