### ISSUE TITLE
Versioned galley redirects to most recent

### ISSUE THREAD

**Issue by bkawula** [pkp/bootstrap3#177]
Hi! Not sure if this has come up before, but I'm using v3.2.0.4 of the plugin on 3.3.0.8 and noticed that when viewing any older version and click that version's galley file, only the most recent version gets displayed / downloaded.

**Comment by NateWr** [comment]
Thanks for the report, @bkawula. It looks like Bootstrap's [galley_link.tpl](https://github.com/NateWr/bootstrap3/blob/master/templates/frontend/objects/galley_link.tpl) never got the versioning updates like the default theme's [galley_link.tpl](https://github.com/pkp/ojs/blob/stable-3_3_0/templates/frontend/objects/galley_link.tpl).

Can you test the changes in https://github.com/NateWr/bootstrap3/commit/0daf8f5be405a5566a0551a29d9ca4d784518f07 and let me know if they work?

**Comment by kaitlinnewson** [comment]
@asmecher This can be closed as resolved in https://github.com/pkp/bootstrap3/commit/0daf8f5be405a5566a0551a29d9ca4d784518f07 (re-tested in 3.3/3.4).

**Comment by asmecher** [comment]
Closing, thanks, @kaitlinnewson!
