### ISSUE TITLE
Author affiliation class on details page has a typo

### ISSUE THREAD

**Issue by rawlins** [pkp/bootstrap3#181]
On [article_details.tpl line 177](https://github.com/NateWr/bootstrap3/blob/0daf8f5be405a5566a0551a29d9ca4d784518f07/templates/frontend/objects/article_details.tpl#L177) (permalink to current trunk at time of writing), `<div class="article-author-affilitation">` should I assume be `<div class="article-author-affiliation">`.

**Comment by kaitlinnewson** [comment]
PR ready for review @asmecher:

- main: https://github.com/pkp/bootstrap3/pull/208

I just did the PR to main as I don't see any styling in the class, but can backport if needed.
