### ISSUE TITLE
Readable theme contains not readable color selection

### ISSUE THREAD

**Issue by dogsleg** [pkp/bootstrap3#192]
Hi,

thanks for your work on Bootstrap Theme for OJS.

Readable theme has a color selection for "Make a new submission or view your pending submissions". Please, see the screenshot attached.

![Readable](https://user-images.githubusercontent.com/2309519/192109697-59a7d662-4a2e-42c0-9d60-b81f33a6e6c6.png)

**Comment by NateWr** [comment]
Thanks for reporting this @dogsleg. I don't have time to address this now but I will try to get a fix for this in when a refactor the theme for 3.4.

**Comment by kaitlinnewson** [comment]
Fix ready for this, which will add the `alert-link` class to links in alert boxes. This improves the display of links across all of the sub-styles as well.

Readable theme with fix (see screenshot above for before):

![Screenshot 2024-06-27 at 11 31 46 AM](https://github.com/pkp/bootstrap3/assets/6903515/91907251-c306-449d-9780-e4181944f285)

Alerts for user registration form before (Readable theme):

![Screenshot 2024-06-27 at 11 40 13 AM](https://github.com/pkp/bootstrap3/assets/6903515/d4c2a86f-32be-4011-8820-e802c1021fb3)

Alerts for user registration form with fix (Readable theme):

![Screenshot 2024-06-27 at 11 39 54 AM](https://github.com/pkp/bootstrap3/assets/6903515/d860e7fb-8918-41e9-aa22-408e2143de39)


@asmecher PR ready for review - will forward-port if all looks good:

- 3_3_0: https://github.com/pkp/bootstrap3/pull/215

**Comment by asmecher** [comment]
^ Merged, thanks, @kaitlinnewson!

**Comment by kaitlinnewson** [comment]
@asmecher Additional PRs linked above and ready for review.

**Comment by asmecher** [comment]
Both merged, thanks! Now that you've got permissions on this repo, you can use your discretion to decide whether ports need additional review; if not, feel free to `git cherry-pick` them forward.
