### ISSUE TITLE
doi not show in bootstap3 and ojs 3.4

### ISSUE THREAD

**Issue by simonevecchi** [pkp/bootstrap3#198]
hi I upgraded to ojs 3.4.0-1 and updated the bootstrap3 template. I have a problem. although I have enabled and configured the datacite doi plugin, the DOI field no longer appears under the pdf button and between the keywords and the date in the articles. the doi field appeared regularly in version 3.3.0.14
why? could you please help me to understand the problem?

this is in 3.4.0-1
<img width="325" alt="Schermata 2023-06-19 alle 15 31 38" src="https://github.com/pkp/bootstrap3/assets/94114976/eaac2529-e609-4f41-a24b-e5b58428d462">
[https://www.journalofgeoethics.eu/jogvm-3.401/index.php/jgsg/article/view/26](url)

this is the same article in 3.3.0.14
<img width="257" alt="Schermata 2023-06-19 alle 21 48 27" src="https://github.com/pkp/bootstrap3/assets/94114976/cdd2f994-5b32-4b95-a067-b6b1096a12ba">
[https://www.journalofgeoethics.eu/index.php/jgsg/article/view/26](url)

if I set the default theme you see the doi instead!
thanks

**Comment by asmecher** [comment]
@simonevecchi, you can resolve this by applying [this change](https://github.com/pkp/bootstrap3/commit/0a129341e6a216a6a71b51a17609dc2e855cbfde) in `plugins/themes/bootstrap3`.
