### ISSUE TITLE
The latest release has an invalid version

### ISSUE THREAD

**Issue by jonasraoni** [pkp/bootstrap3#203]
The latest release (https://github.com/pkp/bootstrap3/releases/tag/v3_4_0-0) has an incorrect version `3.3.0.0` when compared with the plugin gallery (`3.4.0.0`), this leads to the loop: 

```mermaid
graph TD;
  upgrade["Upgrade to 3.4.0 available"]
  download["Download 3.3.0"]
  upgrade-->download;
  download-->upgrade;
```

Also, the link at the plugin-gallery should probably point to this repository instead of https://github.com/NateWr/bootstrap3

Source: https://forum.pkp.sfu.ca/t/plugins-following-update-3-4-0-5/85818/9

**Comment by asmecher** [comment]
Resolved with new release from `stable-3_4_0`.
