### ISSUE TITLE
Missing `Templates::Search::SearchResults::` hooks on search.tpl

### ISSUE THREAD

**Issue by henriquejsfj** [pkp/bootstrap3#204]
There are missing the hooks `Templates::Search::SearchResults::AdditionalFilters` and `Templates::Search::SearchResults::PreResults` that are present on OJS and not in this plugin.

**Comment by kaitlinnewson** [comment]
@asmecher There is currently a PR for this issue on 3_4_0: https://github.com/pkp/bootstrap3/pull/205

Let me know if it looks good and I can back/forward port.

**Comment by asmecher** [comment]
Merged, thanks, @kaitlinnewson -- please go ahead!

**Comment by kaitlinnewson** [comment]
Ported to `3_3_0` and `main`, closing.
