### ISSUE TITLE
Article preview fails if no issue assigned

### ISSUE THREAD

**Issue by jnugent** [pkp/bootstrap3#226]
The theme fails in numerous places if an issue is not assigned and previewing is attempted.  

For example:

https://github.com/pkp/bootstrap3/blob/stable-3_4_0/templates/frontend/components/breadcrumbs_article.tpl#L31

generates a fatal error because the $issue object is null.  Also, e.g. here:

https://github.com/pkp/bootstrap3/blob/stable-3_4_0/templates/frontend/objects/article_details.tpl#L279

There are other places.  Spotted in 3.3 but I am linking to 3.4 versions of the plugin as the problem exists throughout.

**Comment by kaitlinnewson** [comment]
PR to 3.3 ready for review @asmecher - changes are based on the default theme templates: 

- https://github.com/pkp/bootstrap3/pull/227

Will forward-port once approved.

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson, please go ahead! I've merged the `stable-3_3_0` PR.
