### ISSUE TITLE
Fix display of citation block on article page

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/bootstrap3#228]
When the citation plugin has been enabled, the citations are duplicated on the article page. When clicking "More Citation Formats", the list of formats is appearing near the bottom of the page in a very small font.

Issue appears in 3.4/main.

Article page with duplicate citations: 

![Screenshot 2024-09-03 at 10 21 45 AM](https://github.com/user-attachments/assets/8890819f-728e-4100-a115-4b3ab59992be)

After clicking "More Citation Formats": 

![Screenshot 2024-09-03 at 10 21 56 AM](https://github.com/user-attachments/assets/b76ebc17-8198-4ee2-a372-f9fb600e0d92)

**Comment by kaitlinnewson** [comment]
PR for review to 3.4: https://github.com/pkp/bootstrap3/pull/231

@Vitaliy-1 would you be able to give this a quick look? It's similar to what is done in the other themes.

**Comment by asmecher** [comment]
Oof, some good catches there! Sorry for the delay; merged now. Is this ready to be closed, or is there further porting required?

**Comment by kaitlinnewson** [comment]
Forward-ported to main now, closing.
