### ISSUE TITLE
Does the switch to Carbon for handling dates break the bootstrap theme?

### ISSUE THREAD

**Issue by BartChris** [pkp/bootstrap3#235]
Using the Bootstrap 3 theme we get an error when opening the article details page in OJS 3.4.0.8. In OJS 3.4.0.7 it worked.

Could this error be related to the changes done to adress this issue?

https://github.com/pkp/pkp-lib/issues/9303

PHP Fatal error:  Uncaught TypeError: Carbon\\Carbon::translatedFormat(): Argument #1 ($format) must be of type string, null given, called in /var/www/html/lib/pkp/classes/template/PKPTemplateManager.php on line 2044 and defined in /var/www/html/lib/pkp/lib/vendor/nesbot/carbon/src/Carbon/Traits/Date.php:2328\nStack trace:\n#0 /var/www/html/lib/pkp/classes/template/PKPTemplateManager.php(2044): Carbon\\Carbon->translatedFormat()\n#1 /var/www/html/cache/t_compile/5344c657d475ac490e5be9e38a89fff34c6138fd^addd65021fadf964339ab08cd1aa93ba59b14e9c_0.app.frontendobjectsarticle_details.tpl.php(123): PKP\\template\\PKPTemplateManager->smartyDateFormat()\n#2 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_67582fbbc51ab3_73448194()\n#3 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()\n#4 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()\n#5 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render()\n#6 /var/www/html/cache/t_compile/5344c657d475ac490e5be9e38a89fff34c6138fd^1c372c95cd85572e0fbc9a53d0323a0b229cfc78_0.app.frontendpagesarticle.tpl.php(40): Smarty_Internal_Template->_subTemplateRender()\n#7 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_67582fbba9b518_69264237()\n#8 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()\n#9 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()\n#10 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()\n#11 /var/www/html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()\n#12 /var/www/html/lib/pkp/classes/template/PKPTemplateManager.php(1372): Smarty_Internal_TemplateBase->display()\n#13 /var/www/html/pages/article/ArticleHandler.php(355): PKP\\template\\PKPTemplateManager->display()\n#14 [internal function]: APP\\pages\\article\\ArticleHandler->view()\n#15 /var/www/html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()\n#16 /var/www/html/lib/pkp/classes/core/PKPPageRouter.php(278): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#17 /var/www/html/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPPageRouter->route()\n#18 /var/www/html/lib/pkp/classes/core/PKPApplication.php(395): PKP\\core\\Dispatcher->dispatch()\n#19 /var/www/html/index.php(21): PKP\\core\\PKPApplication->execute()\n#20 {main}\n  thrown in /var/www/html/lib/pkp/lib/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 232

**Comment by asmecher** [comment]
@BartChris, could you start with our support forum (https://forum.pkp.sfu.ca) rather than filing an issue? There are a couple of posts with the same message there, so see if you can find an existing solution before posting a new topic.

**Comment by BartChris** [comment]
@asmecher Thanks a lot for your support. I suppose the problem is that the current release does not contain the critical fix of

https://github.com/pkp/bootstrap3/pull/233

which introduces the date formatting which Carbon needs.

https://github.com/kaitlinnewson/bootstrap3/blob/7f7a87d7f0a92c78e919e2eb35f76eaeaf904374/templates/frontend/objects/article_details.tpl#L93

**Comment by asmecher** [comment]
Hi @BartChris -- https://github.com/pkp/bootstrap3/pull/231 is actually the relevant PR for `stable-3_4_0`, but I expect https://github.com/pkp/bootstrap3/pull/233 is probably close enough to identical. The relevant issue is https://github.com/pkp/bootstrap3/issues/228.

**Comment by kaitlinnewson** [comment]
Hi @BartChris, a new version of the plugin is now in the plugin gallery which includes this fix.
